In [1]:
import numpy as np

In [2]:
numbers= np.array([2,3,4,5,7])

In [3]:
type(numbers)

numpy.ndarray

In [4]:
numbers

array([2, 3, 4, 5, 7])

In [7]:
np.array([[1,3,5,7],[2,4,6,8]])

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

# Exercises

In [1]:
np.array(list(i for i in range(1,21) if i%2==0))

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [2]:
np.array([list(i for i in range(1,11)if i%2==0),list(i for i in range(1,11)if i%2!=0)])

array([[ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9]])

# Attributes

In [5]:
integers= np.array([[1,2,3,4],[5,6,7,8]])

In [6]:
integers

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
integers.ndim

2

In [8]:
integers.shape

(2, 4)

In [10]:
integers.itemsize

8

In [12]:
for row in integers:
    for columns in row:
        print(columns,end=' ')

1 2 3 4 5 6 7 8 

In [13]:
for row in integers:
    for columns in row:
        print(columns,end=' ')
    print()

1 2 3 4 
5 6 7 8 


In [7]:
import numpy as np

In [9]:
np.arange(2,41,2).reshape(4,5)

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

In [5]:
import random

In [6]:
%timeit roll_list= [random.randrange(1,7)for i in range(6000000)]

1 loop, best of 5: 5.87 s per loop


In [7]:
%timeit roll_array= np.random.randint(1,7,6000000)

10 loops, best of 5: 62.7 ms per loop


In [12]:
%timeit sum_list=sum([x for x in range(10_000_000)]) 

1 loop, best of 5: 515 ms per loop


In [15]:
%timeit sum_array= np.arange(10_000_000).sum()

100 loops, best of 5: 15.8 ms per loop


In [16]:
numbers= np.arange(1,6)

In [17]:
numbers**2

array([ 1,  4,  9, 16, 25])

In [20]:
grades= np.array([[87,82,89],[76,90,68],[88,77,99]])

In [21]:
grades.sum()

756

In [44]:
Grades= np.array([random.randrange(60,101) for i in range(12)]).reshape(3,4)

In [45]:
Grades

array([[ 71,  61,  95,  97],
       [ 72,  77,  67,  73],
       [ 94,  68, 100,  74]])

In [46]:
Grades.mean()

79.08333333333333

In [47]:
Grades.mean(axis=0)

array([79.        , 68.66666667, 87.33333333, 81.33333333])

In [48]:
Grades.mean(axis=1)

array([81.  , 72.25, 84.  ])

In [49]:
points= np.random.randint(60,101,12).reshape(3,4)

In [50]:
points

array([[86, 62, 79, 96],
       [81, 85, 95, 76],
       [90, 72, 81, 93]])

In [58]:
value=np.array([np.arange(1,6)])

In [59]:
value

array([[1, 2, 3, 4, 5]])

In [61]:
np.power(value,3)

array([[  1,   8,  27,  64, 125]])

In [64]:
sequence=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

In [65]:
sequence

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [68]:
sequence[1]

array([ 6,  7,  8,  9, 10])

In [69]:
sequence[1:3]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [74]:
sequence[:,[1,2]]

array([[ 2,  3],
       [ 7,  8],
       [12, 13]])

In [2]:
a =np.array([np.arange(1,7)]).reshape(2,3)

In [9]:
np.vstack((np.hstack((a,a)),np.hstack((a,a))))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [ ]:
b